import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  if (session) {
    return (
      <html lang="en">
        <body className={`${inter.className} bg-slate-800 text-slate-300`}>
          <SessionProvider session={session}>
            <Navbar />
            {children}
            <Footer />
          </SessionProvider>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body className={`${inter.className} bg-slate-800 text-slate-300`}>
          <SessionProvider session={session}>
            <Navbar />
            <div className="content-height ">
              <h1 className="text-2xl">LANDING</h1>
            </div>
            <Footer />
          </SessionProvider>
        </body>
      </html>
    );
  }
}
